WIP: Add meta tags
helium/explorer pull request #107
Opened 2020-12-01 04:54 UTC by danielcolinjames

Starting work to add meta tags to fix #103 (and #91, #57)

TODO:
- [x] convert `[txnid].js` to use getStaticProps (so the data for the meta tags will be ready at build time, rather than fetching on the client)
- [ ] convert `[blockid].js` to use getStaticProps (same reason as txn page)
- [ ] write out content for each page in a Google Doc
- [ ] make dynamic strings for title, description, etc. for each page and add with `'next/head'` component (through `<MetaTags.js />` probably)
- [ ] make `MetaTags.js` component better and more dynamic
- [ ] add image to each page

Eventually (probably in future PR):
- [ ] make `og:image` for each page dynamic, with our own forked version of [Vercel's `og-image` tool](https://github.com/vercel/og-image)

2020-12-09 00:12 UTC, danielcolinjames commented
Google Doc containing all the different types of pages: https://docs.google.com/document/d/14GRXjlDqKXhvoYnPngtutVyH4K4WLMQKSFk8ZvdSPwI/edit#

2020-12-09 00:15 UTC, danielcolinjames commented
# Links where you can test each kind of meta tag (by putting it into something like [Facebook's debugger tool](https://developers.facebook.com/tools/debug/)):

## Transactions:
### payment_v1:
https://helium-explorer-pr-107.herokuapp.com/txns/6T-kEEiO0KmKQul4HFBHS98qdwXm1UrrQ3oL6x7mTM8

### payment_v2:
https://helium-explorer-pr-107.herokuapp.com/txns/LmCnApgeKkpFLo2J3-FET0FysD6mAqY1Wr6EN5wOjXU

### poc_request_v1
https://helium-explorer-pr-107.herokuapp.com/txns/IJvGDfbQGROJ2ycQwjTXaaGLXbHBEhQQDhaQHNTKkwk

### poc_receipts_v1 with only 1 hotspot:
https://helium-explorer-pr-107.herokuapp.com/txns/tI3XoWXEJTI0USEwugur8RNSUC2DOT0yLTc4gFz_P7k

### poc_receipts_v1 with 4 hops:
https://helium-explorer-pr-107.herokuapp.com/txns/_nf-OOGiMM7fD_hR_1-xBmADPZNTNmQdByM50nEYMKc

### rewards_v1
https://helium-explorer-pr-107.herokuapp.com/txns/HbmLoyZBGai7VsjotYOAP9KP-wrpmOfal8RYyKEMTew

### state_channel_close_v1
https://helium-explorer-pr-107.herokuapp.com/txns/tj5HgInHASt-PUUO5NdniH-09b3BSe3xfzLbAiuEvzM

### state_channel_open_v1
https://helium-explorer-pr-107.herokuapp.com/txns/EFE24whJnD5ThaawPpQxzP4dIECkBUB7KbQhxvIfDMM

### assert_location_v1
https://helium-explorer-pr-107.herokuapp.com/txns/TlyotGbYrC7aB2-39weVcdPy10m6nQTUnxuleWF7a3s

### consensus_group_v1
https://helium-explorer-pr-107.herokuapp.com/txns/bYLJnCHL2bH9eqhipwOE0EjJql_KV_AAJizlBdKQFO4

### add_gateway_v1
https://helium-explorer-pr-107.herokuapp.com/txns/JTTbEw2Ws9VS8rr9T7WDu93KW86YJGffXR7u16jJIyE

### transfer_hotspot_v1
https://helium-explorer-pr-107.herokuapp.com/txns/LEPWBEFqzfclM5UAbQWwlEppZvh9cxo3j8vbUe2gmYI

---
## Account pages:
http://explorer.helium.com/accounts/13VYAAgaeGU393iZ2itUH9V3r6Zeo5atgEPrDQ662KdMmb2XZKw

### With HST:
https://helium-explorer-pr-107.herokuapp.com/accounts/14GWyFj9FjLHzoN3aX7Tq7PL6fEg4dfWPY8CrK8b9S5ZrcKDz6S

### With DC:
https://helium-explorer-pr-107.herokuapp.com/accounts/112vWFJvqjYUbD9nMM8cJepTSHkFHg2AvAgdo2enzif1XgaqzDmp

---
## Hotspot pages:
### With location:
https://helium-explorer-pr-107.herokuapp.com/hotspots/11ZTGE43vuc1mUVgRiYwyELZyc6ByDYfh22BVMWySP6AdkxssHd

### Without location:
https://helium-explorer-pr-107.herokuapp.com/hotspots/112c9FY949P5xeZMdGNf8F8er663Bw94zPmEobxHD6gY8juA7Y2G

---
## Block pages:
https://helium-explorer-pr-107.herokuapp.com/blocks/608425

---
## Blocks:
https://helium-explorer-pr-107.herokuapp.com/blocks

---
## Hotspots:
https://helium-explorer-pr-107.herokuapp.com/hotspots

---
## Market Data:
https://helium-explorer-pr-107.herokuapp.com/market

2020-12-10 03:54 UTC, allenan commented on components/Txns/PaymentV2.js
> +      {txn.fee.floatBalance.toString()} DC
why is this changing to use the floatBalance?  `txn.fee.toString()` should take care of formatting it correctly with the `DC` suffix

2020-12-10 03:54 UTC, allenan commented on components/Txns/PaymentV2.js
> +              ({p.amount.floatBalance.toString()} HNT)
same q

2020-12-10 03:56 UTC, allenan commented on pages/accounts/[accountid].js
> +      description={`An account on the Helium blockchain with ${account.balance.floatBalance.toLocaleString(
all of this type of stringification logic should be taken care of by helium-js. let me know if it's not doing something it's supposed to

2020-12-10 03:57 UTC, allenan commented on pages/blocks/[blockid].js
> +        minimumFractionDigits: 0,
does this need all the config if height is an integer?

2020-12-10 03:58 UTC, allenan commented on pages/blocks/[blockid].js
> +      } of the Helium blockchain was produced on ${moment
should we try to be using `date-fns` for new date logic? generally trying to phase out moment

2020-12-10 04:00 UTC, allenan commented on pages/blocks/[blockid].js
> +        .format('h:mm A')} UTC, with ${txns.length} transaction${
maybe we can extract all of this string logic into helper files? just seems like it's going to be overwhelming in the main page-level components

2020-12-10 04:05 UTC, allenan commented on pages/txns/[txnid].js
> +  switch (txn.type) {
same comment as from the block page. let's think about how we can keep these top level pages from becoming overwhelming. and by breaking out stringification logic into helper files, we can avoid a lot of this verbose switch/ternary logic

2020-12-10 04:06 UTC, allenan requested changes
really excited about the outcome of this PR, but let's take a cycle to clean it up a bit so that it's maintainable going forward

2020-12-10 18:21 UTC, danielcolinjames commented on components/Txns/PaymentV2.js
> +      {txn.fee.floatBalance.toString()} DC
yeah so this was something I noticed when converting the data fetching to use getStaticProps

when trying to pass helium-js's response directly through getStaticProps, I get this:

Error: Error serializing `.txn` returned from `getStaticProps` in "/txns/[txnid]".
Reason: `object` ("[object Object]") cannot be serialized as JSON. Please only return JSON serializable data types.

and one of the fixes seems to be wrapping the response with `JSON.parse(JSON.stringify(response))` but that seems to break that `.toString()` functionality. I'm not entirely sure why, but it seems like something gets lost in the stringify / parse process, but I don't know enough about serialization and what exactly that Next error is saying or how else to solve that

but yeah, the .toString() is definitely the better way to do this. could also potentially have a global helper function for formatting values that takes 2 arguments: value, type

and then we can always use that function to format things like "blockNumber", "hntValue", "dcValue" consistently across the whole Explorer

2020-12-10 18:23 UTC, danielcolinjames commented on pages/blocks/[blockid].js
> +        minimumFractionDigits: 0,
oh this was just to add the thousands separator, since I think it's a bit easier to parse 612,482 than 612482, especially once we get into the millions

but should make sure it's consistent across everywhere we display block numbers

2020-12-10 18:24 UTC, danielcolinjames commented on pages/blocks/[blockid].js
> +      } of the Helium blockchain was produced on ${moment
yeah for sure, will see if I can get rid of moment here. the `moment.utc` was just an easy escape hatch, but yeah should try to use date-fns

2020-12-10 18:25 UTC, danielcolinjames commented on pages/blocks/[blockid].js
> +        .format('h:mm A')} UTC, with ${txns.length} transaction${
yeah for sure, good call

2020-12-10 18:27 UTC, danielcolinjames commented
> really excited about the outcome of this PR, but let's take a cycle to clean it up a bit so that it's maintainable going forward

for sure 👍   appreciate all the good suggestions, will get this cleaned up

2020-12-11 01:35 UTC, jamiew commented
Page titles ftwww

Whenever this gets merged I would recommend adding the site to Google Search Console, if it's not already https://search.google.com/search-console/

2020-12-11 18:28 UTC, allenan commented on pages/blocks/[blockid].js
> +        minimumFractionDigits: 0,
right but I think if it's an integer, you can just call `height.toLocaleString()` without the added config

2020-12-11 18:30 UTC, allenan commented on components/Txns/PaymentV2.js
> +      {txn.fee.floatBalance.toString()} DC
yeah let's look into making the `toString` function in helium-js work properly, if it's not. that way all that logic can happen in once place

2020-12-19 02:22 UTC, danielcolinjames commented
As much as I wanted to get this out this week, I think this one still needs a bit more work, and just wanted to document my thinking / progress here.

In the process of making meta tags for each page, I converted all `/txns` pages' data fetching to use `getStaticProps`. Unfortunately, this creates a bit of a lag when loading a page that hasn't been pre-built. This lag is already present on the other pages that are using `getStaticProps`, and has been documented in a separate issue here: #115 

Next.js has a `fallback: true` option in `getStaticPaths`, (instead of "blocking" which is what it's currently set to—and it blocks loading of the page at all until it's finished building) but `fallback` doesn't quite work the way I was hoping. When navigating between pages on the site, it'll still take awhile to load the page properly, and only shows up if you land on the page with a fresh request, rather than clicking from elsewhere on the site.

I tried out `getServerSideProps` instead of `getStaticProps` for the /blocks and /accounts pages, but that has basically the same behaviour as the "blocking" option for `getStaticPaths`, and it won't cache the pre-built pages any more.

And `fallback` also creates a new issue, because converting the transaction page to this new method of data fetching was about meta tags after all, and if a page hasn't been pre-built yet (as might not be the case with, for example, a hotspot that just got added to the network), then something like the Twitter hotspot bot would have to just show the default meta tags for that hotspot until someone visited that page.

This is an interesting problem and I think worth digging a bit deeper on the data fetching stuff before deploying this. Going to spend some more time thinking about what parts of the data fetching should be client side versus server side. There's probably a happy medium somewhere, where we can keep a lot of the data fetching client-side, but get just enough with `getStaticProps` to populate the meta tags without making the page take a long time to build.

2021-01-12 18:19 UTC, allenan commented on components/Txns/utils.js
> +export const processTransactionInfo = (txn, isFallback) => {
I like to see this complexity compartmentalized into a util module :)

Without some context or looking at the implementation, I'm not really sure what `processTransactionInfo` does from the name. It's very meta tag specific. Maybe something like `metaTagsForTransaction`? `process` is just kinda vague and it'd be good to know at a glance that this has something to do with metatags

2021-01-12 18:21 UTC, allenan commented on pages/accounts/[accountid].js
> +  const dcBalanceWithFunctions = new Balance(
what does the `WithFunctions` part connote here?

2021-01-12 18:23 UTC, allenan commented on pages/hotspots/[hotspotid].js
> +  // // Get most recent challenger transaction
should this commented-out section stick around? is it wip?

2021-01-12 18:24 UTC, danielcolinjames commented on components/Txns/utils.js
> +export const processTransactionInfo = (txn, isFallback) => {
good call! agreed

2021-01-12 18:25 UTC, danielcolinjames commented on pages/accounts/[accountid].js
> +  const dcBalanceWithFunctions = new Balance(
yeah probably not the best naming, but meant the functions like ".toString()" coming from helium-js ... will see if I can think of something more appropriate and rename all the places I used this pattern

2021-01-12 18:26 UTC, danielcolinjames commented on pages/hotspots/[hotspotid].js
> +  // // Get most recent challenger transaction
woops! totally forgot to remove that after moving it all to client-side, good catch

2021-01-12 19:27 UTC, danielcolinjames commented on pages/accounts/[accountid].js
> +  const dcBalanceWithFunctions = new Balance(
replacing "WithFunctions" with "Object" to hopefully make it a bit clearer. I mostly just wanted to distinguish it as a Balance object from helium-js when there were other variables called `fee` or `amount` in the same file

2021-01-12 20:29 UTC, allenan approved these changes
🔥

2021-01-12 20:30 UTC, merged