Prettify token_burn_v1
helium/explorer pull request #155
Opened 2021-01-26 09:35 UTC by filoozom

Fixes #149.

I temporarily set the color to `#FF1A00`, will change based on @cokes518 guidance.

There is no error handling on the oracle price query yet. Do you have any suggestions regarding that part? Maybe I should create a default `Balance` of 0 USD for `oraclePrice` instead of having an `undefined` value and conditionally rendering it?

2021-01-27 19:39 UTC, danielcolinjames commented
this is looking amazing @filoozom! 😄  🔥   nice work!

just made a couple small suggestions, the loading one isn't necessary but might be a bit nicer than having that field be blank for now

and this is more a note-to-self because I can always do this later so no pressure to add it into this PR unless you feel compelled to, but it would be cool to make it show the USD price / oracle price in the ActivityList "Details" column for token burns, which would involve adding a new `case` to the `switch` statement on line 201 of `/components/ActivityList.js`

but like I said, really no pressure to do that for this one unless you want to, as the structure of Ant Design tables and columns can actually be pretty confusing haha

2021-01-27 19:45 UTC, danielcolinjames requested changes
woops, forgot to hit "submit" on the review, my bad!

2021-01-27 19:45 UTC, danielcolinjames commented on components/Txns/TokenBurnV1.js
> +
maybe there could be an `oraclePriceLoading` variable as well, that defaults to true and gets set as false once the useEffect completes? and then when it's true we could conditionally show a 1-line Ant Design skeleton in place of the values in the table that are dependent on the oracle price

for an example of how to add that skeleton you could look here: https://github.com/helium/explorer/pull/152/files

this is what I did to get a little 1-liner loading skeleton (had to override some Ant Design styling):

```jsx
            <span className="inline-skeleton-override">
              <Skeleton active paragraph={{ rows: 0 }} size="small" />
            </span>
```

2021-01-27 19:45 UTC, danielcolinjames commented on components/Txns/TxnTag.js
> +      return <Tag color="#FF1A00">Token Burn</Tag>
I think red makes sense 🔥   I just pulled #E86161 from an internal Figma file, might look a little less harsh for now if Coco doesn't get back to us :)

2021-01-28 16:44 UTC, filoozom commented on components/Txns/TokenBurnV1.js
> +
Guess I'll wait for #152 to be merged to patch that one? I didn't realize that it wasn't there yet, so I rewrote the CSS to find out that I basically ended up with the same you had 😝

2021-01-28 21:45 UTC, danielcolinjames commented on components/Txns/TokenBurnV1.js
> +
sorry I should've made it clear that that was an open PR 😛   you can add it to this PR if you want, as the other one still needs a bit of work before it's ready to go

(or we can just ship this as is — still much better than the current JSON dump)

2021-01-28 21:46 UTC, danielcolinjames approved these changes

2021-01-29 12:40 UTC, filoozom commented on components/Txns/TokenBurnV1.js
> +
Alright, I took #152's Explorer.css file and added the skeleton 🙂

2021-01-30 02:32 UTC, danielcolinjames commented
great work @filoozom! you're the first to close a hackathon PR so I'm not sure what exactly our process will be like for the swag, but we'll figure it out on monday and I'll put you in touch with the marketing team 😄  (please remind me if I forget)

2021-01-30 02:33 UTC, merged