Add reward scale to hotspot page
helium/explorer pull request #165
Opened 2021-01-29 02:15 UTC by danielcolinjames

Closes #119 

Here's how I implemented it for now (happy to make changes):

![Screen Shot 2021-01-28 at 6 10 27 PM](https://user-images.githubusercontent.com/10648471/106222482-73283100-6194-11eb-9bec-9cdea0cfcf52.png)

![Screen Shot 2021-01-28 at 6 11 17 PM](https://user-images.githubusercontent.com/10648471/106222486-74595e00-6194-11eb-9de8-0576a2e72e16.png)

![Screen Shot 2021-01-28 at 6 11 55 PM](https://user-images.githubusercontent.com/10648471/106222487-74595e00-6194-11eb-89ea-3ce032a409bf.png)

![Screen Shot 2021-01-28 at 6 12 01 PM](https://user-images.githubusercontent.com/10648471/106222489-74f1f480-6194-11eb-9f7c-1aff4c52ce35.png)

![Screen Shot 2021-01-28 at 6 12 06 PM](https://user-images.githubusercontent.com/10648471/106222491-74f1f480-6194-11eb-9d9f-1b9fe16f0d97.png)

And this is the colour scale I used, but I'm not sure if this is the best approach or the best colours to use:
![Screen Shot 2021-01-28 at 6 13 52 PM](https://user-images.githubusercontent.com/10648471/106222550-9fdc4880-6194-11eb-8b9a-20dbd7f136e3.png)

2021-01-29 02:59 UTC, DGKSK8LIFE requested changes
I like it, but maybe remove the background transparency on the hover-over reward scale indicator

2021-01-29 18:59 UTC, allenan approved these changes
this is good. let's also see where else in the explorer we can propagate this data. ie account -> hotspots table, coverage map, hotspot -> witnesses/nearby tables etc

2021-01-29 22:36 UTC, amirhaleem commented
> this is good. let's also see where else in the explorer we can propagate this data. ie account -> hotspots table, coverage map, hotspot -> witnesses/nearby tables etc

the PoC receipt txn would be good too

2021-01-29 22:38 UTC, abhay commented
There's some edge case here where a hotspot that is still syncing may not have a rewards scale

Current example: https://explorer.helium.com/hotspots/112vU2y2hUop9BSommZEB4EFe8GHVA5Ly93uTLBTaYwkdcGKyccd
vs 
https://helium-explorer-pr-165.herokuapp.com/hotspots/112vU2y2hUop9BSommZEB4EFe8GHVA5Ly93uTLBTaYwkdcGKyccd

https://api.helium.io/v1/hotspots/112vU2y2hUop9BSommZEB4EFe8GHVA5Ly93uTLBTaYwkdcGKyccd
```
{"data":{"lng":-112.22785813507383,"lat":33.57715947773545,"timestamp_added":"2021-01-29T22:08:29.000000Z","status":{"online":"online","listen_addrs":["/p2p/112HQSHGMaR9jRv45vjbXe3EUvxfDDhXTWTRunvegqgABA3kByLj/p2p-circuit/p2p/112vU2y2hUop9BSommZEB4EFe8GHVA5Ly93uTLBTaYwkdcGKyccd"],"height":1},"reward_scale":null,"owner":"14hUXDqxyxTK7osDrj3WSCpq2ynZb4nHnxvsAdsYYMtd1W8pC93","nonce":1,"name":"joyous-grape-woodpecker","location":"8c29b6d5582a3ff","last_poc_challenge":null,"last_change_block":697125,"geocode":{"short_street":"W Brown St","short_state":"AZ","short_country":"US","short_city":"Peoria","long_street":"West Brown Street","long_state":"Arizona","long_country":"United States","long_city":"Peoria","city_id":"cGVvcmlhYXJpem9uYXVuaXRlZCBzdGF0ZXM"},"block_added":697124,"block":697149,"address":"112vU2y2hUop9BSommZEB4EFe8GHVA5Ly93uTLBTaYwkdcGKyccd"}}
```

2021-01-29 22:38 UTC, cokes518 commented
https://github.com/helium/explorer/issues/116 here's the specifics for including reward scale in a poc transaction

2021-01-29 22:48 UTC, waveform06 commented
There are many people who are assuming "a scale of 0.5 means your hotspot earnings are halved" on discord, reddit etc. Scale needs a better public explanation of what it means to your earnings.

2021-01-30 01:05 UTC, danielcolinjames commented
> There's some edge case here where a hotspot that is still syncing may not have a rewards scale
> 
> Current example: https://explorer.helium.com/hotspots/112vU2y2hUop9BSommZEB4EFe8GHVA5Ly93uTLBTaYwkdcGKyccd
> vs
> https://helium-explorer-pr-165.herokuapp.com/hotspots/112vU2y2hUop9BSommZEB4EFe8GHVA5Ly93uTLBTaYwkdcGKyccd
> 
> ```shell
> $ http GET https://api.helium.io/v1/hotspots/112vU2y2hUop9BSommZEB4EFe8GHVA5Ly93uTLBTaYwkdcGKyccd | jq -r '.data.rewards_scale'
> null
> ```

@abhay  oh hmm, are you saying there isn't a reward_scale field when the hotspot is still syncing? I'm seeing `reward_scale: 1` when I ping that URL

2021-02-03 21:48 UTC, merged