Make the PieChart colors match their tags
helium/explorer pull request #170
Opened 2021-01-29 23:27 UTC by filoozom

Fixes #37.

2021-02-01 23:52 UTC, danielcolinjames requested changes
great work! just had a few small comments but nothing major, works pretty nicely and definitely a big improvement over the current pie chart already :)

2021-02-01 23:52 UTC, danielcolinjames commented on components/Txns/TxnTag.js
> +  assert_location_v1: '#595a9a',
looks like `assert_location_v1` is given a new colour here than it had before? that's fine (and probably a better colour since the other one was probably failing valid accessible contract ratio), just wanted to make it was intentional

2021-02-01 23:52 UTC, danielcolinjames commented on components/Txns/TxnTag.js
> +  default: 'blue',
I think the `default` won't get triggered unless we use it down below on line 25 like:
```js
color={COLORS[type] || 'blue'}
```

2021-02-01 23:52 UTC, danielcolinjames commented on components/Txns/TxnTag.js
>      case 'transfer_hotspot_v1':
I think this one was supposed to be removed too?

2021-02-01 23:52 UTC, danielcolinjames commented on components/Txns/TxnTag.js
> +export const COLORS = {
I think a few of the hex codes got switched around, might want to double check them (or if it was intentional that's fine)

we'll probably at some point come up with a proper colour palette for all types of transactions that can be consistent across the app and Explorer, so the way you refactored it here will make that a lot easier :)

2021-02-02 00:10 UTC, filoozom commented on components/Txns/TxnTag.js
> +export const COLORS = {
Huh, how did that happen 😅 Definitely was not intentional, I apologise for those mistakes, should definitely have double checked!

Regarding the refactoring, I might actually change it a bit more to a `CONFIG` variable that also includes the names, so that they could be re-used in the Pie Chart or in filters. Right now you either use the "API name" (in the Pie Chart) or copy the names (in the filter).

2021-02-02 00:11 UTC, filoozom commented on components/Txns/TxnTag.js
> +  default: 'blue',
You're perfectly right, I guess I forgot about that one.

2021-02-02 00:15 UTC, danielcolinjames commented on components/Txns/TxnTag.js
> +export const COLORS = {
no worries! :)

and yeah that sounds like a good plan, love it 👍

2021-02-04 22:39 UTC, danielcolinjames approved these changes
nicely done! the refactor with CONFIG makes a lot of sense and should help make it more reusable—good call 🙂

2021-02-04 22:39 UTC, merged