ISSUE-174: Added scale to Mapbox Components
helium/explorer pull request #177
Opened 2021-02-03 13:58 UTC by nickhough

Added ScaleControl to Mapbox on both the CoverageMap and HotspotMapbox components.

2021-02-03 20:31 UTC, danielcolinjames requested changes
nice! didn't even know about ScaleControl, this is a great addition 😄 

the only thing I think would make it better is if it would be possible to style it a bit differently, ideally with a transparent background and white text for the number, or something like that. not sure what kind of styling options there are, but I think right now it sticks out a little bit too much in terms of the visual design

I didn't look at the documentation so I'm not sure the best way to do it, but in case you have to override it or do it manually, I've had to override a few Ant Design things by wrapping them with a `<span>` with a given class name and then target the appropriate Mapbox class as a child of that span in explorer.css (not sure if I described that well—and there's probably better approaches anyway)

2021-02-03 20:33 UTC, nickhough commented
@danielcolinjames I'll take a peek at the docs and see if I can style it up to match a bit better.

2021-02-03 20:37 UTC, danielcolinjames commented
awesome, happy to provide any input if that would be helpful :)

2021-02-04 14:18 UTC, nickhough commented
@danielcolinjames The ReactMapboxGl component only exposes styles for the container, not the content, so I was only able to adjust the container backgroundColor. I tried a transparent background, but it didn't look very good with the dark content, so I just went with one of the other colors being used in the CoverageMap.

2021-02-04 14:20 UTC, nickhough commented
@danielcolinjames I didn't attempt the `span` method you referenced, but if you're not good with how it looks, I can give that a shot as well.

2021-02-04 18:40 UTC, danielcolinjames commented
perfect! that's so much better than my span method haha. looks fantastic. I added a couple lines to make the text white and I think it works okay when it's transparent as long as the text is white and our maps stay dark :) might be a little hard to read in some scenarios (if it's right over a cluster of the bright green dots for example), but since I don't imagine it'll be used by _everyone_, I just think it looks a little less intrusive without a background

oh and I also rewrote it as a functional component just to be consistent with most of our newest components

this is fantastic though, great work! 😄  🔥

2021-02-04 18:40 UTC, danielcolinjames approved these changes

2021-02-04 18:43 UTC, merged

2021-02-04 18:44 UTC, nickhough commented on components/ScaleControl.js
> +      color: 'white',
@danielcolinjames Didn't think the ScaleControl was utilizing this. Awesome!

2021-02-04 18:46 UTC, danielcolinjames commented on components/ScaleControl.js
> +      color: 'white',
yeah to be honest I was surprised it worked! haha might just be because the underlying html is just a couple of divs and all of them get their parent's styles, so probably wouldn't have worked for a more complicated component 😆  but for now should be fine