Display offline hotspots in red on the map
helium/explorer pull request #225
Opened 2021-02-23 10:14 UTC by filoozom

Fixes #109.

2021-02-23 23:37 UTC, danielcolinjames commented on pages/api/coverage.js
> +  const [onlineHotspots, offlineHotspots] = hotspots.reduce(
very nice. no comment really, just appreciating this elegant little piece of code :)

2021-02-23 23:40 UTC, filoozom commented on pages/api/coverage.js
> +  const [onlineHotspots, offlineHotspots] = hotspots.reduce(
Well, lately I've been wondering if it isn't better to just write a plain simple `for` loop that is way easier to think about for everyone, but I also quite like this solution 😛

2021-02-23 23:47 UTC, danielcolinjames commented on pages/api/coverage.js
> +  const [onlineHotspots, offlineHotspots] = hotspots.reduce(
haha possibly. but yeah this actually made me realize, since it's already nicely split into two arrays, we could even show a little check box underneath the total hotspots number in sidebar that says "Include offline hotspots" and when you uncheck it, all the red ones could just disappear, and the number in the top left could change to show the total number of online hotspots

but that's probably better for another PR after this one haha

2021-02-23 23:49 UTC, filoozom commented on pages/api/coverage.js
> +  const [onlineHotspots, offlineHotspots] = hotspots.reduce(
Definitely. Should be straightforward, I'm just not too sure about the design.

2021-02-24 00:06 UTC, danielcolinjames requested changes
looking great! just a few small suggestions, some of which I know you're already aware of :)

this is a great addition 🔥  nice work!

2021-02-24 10:10 UTC, filoozom commented on components/CoverageMap/CoverageMap.js
>          />
Done. There's a slight delay before the color gets adjusted, but I don't know if I can do anything about it. 😞 I think in our code the color and hotspots are always synchronized, so I have a feeling that the issue comes from `GeoJSONLayer`?

2021-02-24 10:10 UTC, filoozom commented on pages/api/coverage.js
> +  return { online, offline }
Done, I only show the online ones.

2021-02-24 16:00 UTC, danielcolinjames approved these changes
looks good! 🔥

2021-02-24 16:01 UTC, merged