Update communitytools.js
helium/explorer pull request #585
Opened 2021-07-24 16:40 UTC by nickhough

Added HeliumVision.

2021-07-26 19:34 UTC, danielcolinjames requested changes
looks good! only small request is could you remove Optimization as a tag?

we decided "Planning" was a better abstracted catch-all term for optimization / planning related things for now. and there's also only styling/colors for the current 3 tags so I'm actually not sure how it'll style a tag that's not in the list yet 😅 

we can definitely revisit the categories as the list grows but for now I think just Planning makes sense

2021-07-27 15:27 UTC, nickhough commented
@danielcolinjames Done!

2021-07-27 21:18 UTC, allenan approved these changes

2021-07-27 21:23 UTC, danielcolinjames approved these changes

2021-07-27 21:25 UTC, merged